export const INPUT_CONTAINER_MARGIN = 5;
export const INPUT_CONTAINER_PADDING = 10;
export const APP_CONTAINER_MARGIN_HORIZONTAL = 4;
export const APP_CONTAINER_MARGIN_TOP = 45;
export const BORDER_COLOR = '#797B4B';
export const INPUT_BACKGROUND_COLOR = '#FEFFE1';
export const TEXT_COLOR ='#1D3C03'
export const BACKGROUND_COLOR ='#f2e5d5';
export const FOOD_TEXT_COLOR = "white" ;
